### ISSUE TITLE
Error is thrown when deserializing a tweet containing a url with curly brackets

### ISSUE THREAD

**Issue by seinecle** [twitterdev/twitter-api-java-sdk#16]
URISyntaxException when deserializing a String containing curly brackets

### Expected behavior
Deserialization should work

### Actual behavior
An exception is thrown:
```
com.google.gson.JsonIOException: java.net.URISyntaxException: Illegal character in query at index 32: http://lp.ixd.dmm.com/lp/?lpurl={lurl}
	at com.google.gson.internal.bind.TypeAdapters$22.read(TypeAdapters.java:523)
	at com.google.gson.internal.bind.TypeAdapters$22.read(TypeAdapters.java:512)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
	at com.twitter.clientlib.model.UrlEntity$CustomTypeAdapterFactory$1.read(UrlEntity.java:543)
	at com.twitter.clientlib.model.UrlEntity$CustomTypeAdapterFactory$1.read(UrlEntity.java:532)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
	at com.twitter.clientlib.model.FullTextEntities$CustomTypeAdapterFactory$1.read(FullTextEntities.java:357)
	at com.twitter.clientlib.model.FullTextEntities$CustomTypeAdapterFactory$1.read(FullTextEntities.java:346)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
	at com.twitter.clientlib.model.Tweet$CustomTypeAdapterFactory$1.read(Tweet.java:867)
	at com.twitter.clientlib.model.Tweet$CustomTypeAdapterFactory$1.read(Tweet.java:856)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
	at com.twitter.clientlib.model.TweetSearchResponse$CustomTypeAdapterFactory$1.read(TweetSearchResponse.java:325)
	at com.twitter.clientlib.model.TweetSearchResponse$CustomTypeAdapterFactory$1.read(TweetSearchResponse.java:314)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	at com.google.gson.Gson.fromJson(Gson.java:956)
	at com.google.gson.Gson.fromJson(Gson.java:905)
	at com.twitter.clientlib.JSON.deserialize(JSON.java:921)
```

### Steps to reproduce the behavior
Query recent tweets where one tweet includes a url with curly braces (see the first line of the error trace). This happened when I did a test with a query on "Obama". Can't redo the query as the tweet is no longer included in the nth most recent tweets

**Comment by zacmos** [comment]
Hi, the url fields inside Tweet.entities are a `"format" : "uri"`
The generated Java object contains these fields as type `URI` therefore the exception is valid.
The question is how does the system enables creation of a non valid url, I didn't manage to create one using the UI. I'll have to check it more deeper.
At the moment, I don't see it as an SDK issue.

**Comment by totetmatt** [comment]
Got same kind of issue with url from a tweet during the  `FilteredStreamingTweet.fromJson` .

```
WARNING [fr.totetmatt.gephi.twitter.utils.listener.filtered.TweetsStreamListenersExecutor]: java.net.URISyntaxException: Illegal character in fragment at index 259: https://www.leparisien.fr/international/guerre-en-ukraine-les-russes-veulent-tout-detruire-dans-le-donbass-martele-zelensky-washington-refuse-les-dollars-russes-suivez-notre-direct-25-05-2022-35MUTX4UQJEPHB5SICS4NP4EUA.php#b584c9a1-2670-469a-bf39-e64a80744207#xtor=AD-1481423553
```

I try with a simple code stub using `java.net.URI`, it effectively raise an exception. But it would works with `java.net.URL` , I tried with my entry and seinecle's one, both works.

Do you think it would be beneficial to then change the definition of the tweet entities url as `java.net.URL` ?

**Comment by zacmos** [comment]
Thank you, I'll check it.

**Comment by zacmos** [comment]
Regarding the URI exception, version 1.2.3 uses URLs.
