### ISSUE TITLE
IllegalAccessError exception 

### ISSUE THREAD

**Issue by manushakaru** [twitterdev/twitter-api-java-sdk#26]
I used TweetsStreamListenersExecutor example to fetch tweets and got the below exception.  

### Exception 

Should throw the exception 

Exception in thread "Thread-118" java.lang.IllegalAccessError: class io.gsonfire.gson.HooksTypeAdapter (in unnamed module @0x3f64b8f4) cannot access class com.google.gson.internal.bind.JsonTreeReader (in module com.google.gson) because module com.google.gson does not export com.google.gson.internal.bind to unnamed module @0x3f64b8f4
	at io.gsonfire.gson.HooksTypeAdapter.deserialize(HooksTypeAdapter.java:84)
	at io.gsonfire.gson.HooksTypeAdapter.read(HooksTypeAdapter.java:54)
	at com.google.gson@2.9.0/com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson@2.9.0/com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson@2.9.0/com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson@2.9.0/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson@2.9.0/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson@2.9.0/com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
	at twitter.api.java.sdk@1.2.4/com.twitter.clientlib.model.FilteredStreamingTweet$CustomTypeAdapterFactory$1.read(FilteredStreamingTweet.java:326)
	at twitter.api.java.sdk@1.2.4/com.twitter.clientlib.model.FilteredStreamingTweet$CustomTypeAdapterFactory$1.read(FilteredStreamingTweet.java:315)
	at com.google.gson@2.9.0/com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson@2.9.0/com.google.gson.Gson.fromJson(Gson.java:991)
	at com.google.gson@2.9.0/com.google.gson.Gson.fromJson(Gson.java:956)
	at com.google.gson@2.9.0/com.google.gson.Gson.fromJson(Gson.java:905)
	at com.google.gson@2.9.0/com.google.gson.Gson.fromJson(Gson.java:876)
	at twitter.api.java.sdk@1.2.4/com.twitter.clientlib.model.FilteredStreamingTweet.fromJson(FilteredStreamingTweet.java:341)
	at com.numex/com.numex.util.twitterclient.TweetsStreamListenersExecutor$TweetsQueuer.queueTweets(TweetsStreamListenersExecutor.java:101)
	at com.numex/com.numex.util.twitterclient.TweetsStreamListenersExecutor$TweetsQueuer.run(TweetsStreamListenersExecutor.java:87)

**Comment by zacmos** [comment]
I saw this [link](https://stackoverflow.com/questions/70530938/error-when-trying-to-convert-java-object-to-json-string-using-gson), does it help?
Do you manage to run the example outside of your project, without this issue?

**Comment by manushakaru** [comment]
hi @zacmos 
Thanks for your reply. 

I have tried your solution but it didn't fix the issue. The error is not for all the tweets I receive. It is for some tweets. So, may be this is due to json mismatch. Could you please check this. I haven't tried the example outside the project. I'll try to do it as well. 

Thank you

**Comment by manushakaru** [comment]
Hi @zacmos 

1) I have done some changes 
2) Sure. I'm doing it.
3) Sure 

thanks for the reply. I'll get back to you with proper investigation.

**Comment by zacmos** [comment]
Hi @manushakaru, any updates?
