### ISSUE TITLE
java.lang.IllegalArgumentException: The required field `id` is not found in the JSON string

### ISSUE THREAD

**Issue by Kahen** [twitterdev/twitter-api-java-sdk#28]
抓用户信息的时候，mention 字段并没有 id 这个字段，但是openapiRequiredFields.add("id");将他加上去了，请检查 MentionEntity.java

### Expected behavior

java.lang.IllegalArgumentException: The required field `id` is not found in the JSON string

### Actual behavior

```java
public static Set<String> userFields = Set.of(
            "created_at", "description", "entities", "id", "location", "name", "pinned_tweet_id", "profile_image_url", "protected", "public_metrics", "url", "username", "verified", "withheld"
    );

try {

            Get2UsersIdResponse userById = instance.users().findUserById("276372500").userFields(TwitterFields.userFields).execute();
            User user = userById.getData();
            Assert.assertNotNull(user);
        } catch (ApiException e) {
            throw new RuntimeException(e);
        }
```
当添加了entities字段时，就会因检测id字段而出错
完整报错如下：
```log

java.lang.IllegalArgumentException: The required field `id` is not found in the JSON string: {"start":31,"end":43,"username":"MCNVentures"}

	at com.twitter.clientlib.model.MentionEntity.validateJsonObject(MentionEntity.java:259)
	at com.twitter.clientlib.model.FullTextEntities.validateJsonObject(FullTextEntities.java:369)
	at com.twitter.clientlib.model.UserEntities.validateJsonObject(UserEntities.java:192)
	at com.twitter.clientlib.model.User.validateJsonObject(User.java:568)
	at com.twitter.clientlib.model.Get2UsersIdResponse.validateJsonObject(Get2UsersIdResponse.java:232)
	at com.twitter.clientlib.model.Get2UsersIdResponse$CustomTypeAdapterFactory$1.read(Get2UsersIdResponse.java:273)
	at com.twitter.clientlib.model.Get2UsersIdResponse$CustomTypeAdapterFactory$1.read(Get2UsersIdResponse.java:263)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:928)
	at com.google.gson.Gson.fromJson(Gson.java:877)
	at com.twitter.clientlib.JSON.deserialize(JSON.java:944)
	at com.twitter.clientlib.ApiClient.deserialize(ApiClient.java:959)
	at com.twitter.clientlib.ApiClient.handleResponse(ApiClient.java:1190)
	at com.twitter.clientlib.ApiClient.execute(ApiClient.java:1091)
	at com.twitter.clientlib.api.UsersApi.findUserByIdWithHttpInfo(UsersApi.java:347)
	at com.twitter.clientlib.api.UsersApi.access$500(UsersApi.java:76)
	at com.twitter.clientlib.api.UsersApi$APIfindUserByIdRequest.execute(UsersApi.java:430)
	at com.mifengcha.core.client.TwitterClientTest.testTwitterUser(TwitterClientTest.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)


```

**Comment by zacmos** [comment]
Thanks, will fix it soon.
