### ISSUE TITLE
IllegalArgumentException when no rules returned

### ISSUE THREAD

**Issue by Onedy** [twitterdev/twitter-api-java-sdk#33]
When I call TwitterApi.tweets().getRules().execute() and the API doesn't have rules to return, the SDK fails parsing the result:

java.lang.IllegalArgumentException: The required field `data` is not found in the JSON string: {"meta":{"sent":"2022-07-08T14:41:31.273Z","result_count":0}}
	at com.twitter.clientlib.model.RulesLookupResponse.validateJsonObject(RulesLookupResponse.java:202)
	at com.twitter.clientlib.model.RulesLookupResponse$CustomTypeAdapterFactory$1.read(RulesLookupResponse.java:244)
	at com.twitter.clientlib.model.RulesLookupResponse$CustomTypeAdapterFactory$1.read(RulesLookupResponse.java:234)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	at com.google.gson.Gson.fromJson(Gson.java:956)
	at com.google.gson.Gson.fromJson(Gson.java:905)
	at com.twitter.clientlib.JSON.deserialize(JSON.java:944)
	at com.twitter.clientlib.ApiClient.deserialize(ApiClient.java:959)
	at com.twitter.clientlib.ApiClient.handleResponse(ApiClient.java:1190)
	at com.twitter.clientlib.ApiClient.execute(ApiClient.java:1091)
	at com.twitter.clientlib.api.TweetsApi.getRulesWithHttpInfo(TweetsApi.java:1492)
	at com.twitter.clientlib.api.TweetsApi.access$2500(TweetsApi.java:87)
	at com.twitter.clientlib.api.TweetsApi$APIgetRulesRequest.execute(TweetsApi.java:1573)
	... 9 more

It seems that the API not serializing empty fields causes the ApiClient to fail.

**Comment by zacmos** [comment]
Fixed in V2.0.2
