### ISSUE TITLE
Systematic 401 unauthorized with tweetsRecentSearch and bearer token

### ISSUE THREAD

**Issue by bschnider** [twitterdev/twitter-api-java-sdk#36]
I do not manage to extract the recent tweets of a specific Twitter account with the method `tweetsRecentSearch`, but the same request with `curl` works.

### The `curl` request:

```
curl --request GET 'https://api.twitter.com/2/tweets/search/recent?query=from:elonmusk' --header 'Authorization: Bearer $bearer'
{"data":[{"id":"1547102805600632832","text":"@cb_doge Ancient times"},{"id":"1547094594466332672","text":"Was just up in the booster propulsion section. Damage appears to be minor, but we need to inspect all the engines. Best to do this in the high bay."},{"id":"1547093032301985794","text":"Starship launch site tonight https://t.co/Len70RGCNf"},{"id":"1547081728979869697","text":"@Teslarati @ResidentSponge Join our underground movement!"},{"id":"1547028854161788929","text":"Excited about @NASAWebb potential!"},{"id":"1547002861942448128","text":"@ashleevance https://t.co/fEyGfy1EaX"},{"id":"1547001325602443264","text":"@ashleevance Lmaooo"},{"id":"1546980241494745100","text":"Oh the irony lol"},{"id":"1546957550670815234","text":"@ajtourville @Tesla No problem to recycle the 4680 pack. Just think of any battery pack as super high grade ore – it is always better to start with high grade ore than low grade!"},{"id":"1546733355336716289","text":"@cb_doge But Fifth Element was great"}],"meta":{"newest_id":"1547102805600632832","oldest_id":"1546733355336716289","result_count":10,"next_token":"b26v89c19zqg8o3fpz2mviz0d9x8fxli8oqobs81ze5bx"}}
```

### The same request with `tweetsRecentSearch` systematically returns a status code 401. My code:

```
TwitterCredentialsBearer credentials = new TwitterCredentialsBearer(System.getenv("$bearer"));
TwitterApi apiInstance = new TwitterApi(credentials);
String query = "from:elonmusk";

try {
    Get2TweetsSearchRecentResponse result = apiInstance.tweets().tweetsRecentSearch(query).execute();
    System.out.println(result);
} catch (ApiException e) {
    System.err.println("Exception when calling UsersApi#findUsersById");
    System.err.println("Status code: " + e.getCode());
    System.err.println("Reason: " + e.getResponseBody());
    System.err.println("Response headers: " + e.getResponseHeaders());
    e.printStackTrace();
}
```

### The output:

```
2022-07-13 15:38:35.598 6065-6276/com.example.trackmycrypto W/System.err: Exception when calling UsersApi#findUsersById
2022-07-13 15:38:35.598 6065-6276/com.example.trackmycrypto W/System.err: Status code: 401
2022-07-13 15:38:35.598 6065-6276/com.example.trackmycrypto W/System.err: Reason: {
2022-07-13 15:38:35.598 6065-6276/com.example.trackmycrypto W/System.err:   "title": "Unauthorized",
2022-07-13 15:38:35.598 6065-6276/com.example.trackmycrypto W/System.err:   "type": "about:blank",
2022-07-13 15:38:35.598 6065-6276/com.example.trackmycrypto W/System.err:   "status": 401,
2022-07-13 15:38:35.598 6065-6276/com.example.trackmycrypto W/System.err:   "detail": "Unauthorized"
2022-07-13 15:38:35.598 6065-6276/com.example.trackmycrypto W/System.err: }
2022-07-13 15:38:35.598 6065-6276/com.example.trackmycrypto W/System.err: Response headers: {cache-control=[no-cache, no-store, max-age=0], content-length=[99], content-type=[application/problem+json], date=[Wed, 13 Jul 2022 13:38:35 GMT], server=[tsa_o], x-connection-hash=[5a5e0270ede245b52cb3e53de7617bce341005b413a746f711b9096d54a2e80b], x-response-time=[107]}
2022-07-13 15:38:35.599 6065-6276/com.example.trackmycrypto W/System.err: com.twitter.clientlib.ApiException: Message: 
2022-07-13 15:38:35.599 6065-6276/com.example.trackmycrypto W/System.err: HTTP response code: 401
2022-07-13 15:38:35.599 6065-6276/com.example.trackmycrypto W/System.err: HTTP response body: {
2022-07-13 15:38:35.599 6065-6276/com.example.trackmycrypto W/System.err:   "title": "Unauthorized",
2022-07-13 15:38:35.599 6065-6276/com.example.trackmycrypto W/System.err:   "type": "about:blank",
2022-07-13 15:38:35.599 6065-6276/com.example.trackmycrypto W/System.err:   "status": 401,
2022-07-13 15:38:35.600 6065-6276/com.example.trackmycrypto W/System.err:   "detail": "Unauthorized"
2022-07-13 15:38:35.600 6065-6276/com.example.trackmycrypto W/System.err: }
2022-07-13 15:38:35.600 6065-6276/com.example.trackmycrypto W/System.err: HTTP response headers: {cache-control=[no-cache, no-store, max-age=0], content-length=[99], content-type=[application/problem+json], date=[Wed, 13 Jul 2022 13:38:35 GMT], server=[tsa_o], x-connection-hash=[5a5e0270ede245b52cb3e53de7617bce341005b413a746f711b9096d54a2e80b], x-response-time=[107]}
2022-07-13 15:38:35.600 6065-6276/com.example.trackmycrypto W/System.err:     at com.twitter.clientlib.ApiClient.handleResponse(ApiClient.java:1201)
2022-07-13 15:38:35.600 6065-6276/com.example.trackmycrypto W/System.err:     at com.twitter.clientlib.ApiClient.execute(ApiClient.java:1091)
2022-07-13 15:38:35.600 6065-6276/com.example.trackmycrypto W/System.err:     at com.twitter.clientlib.api.TweetsApi.tweetsRecentSearchWithHttpInfo(TweetsApi.java:4235)
2022-07-13 15:38:35.600 6065-6276/com.example.trackmycrypto W/System.err:     at com.twitter.clientlib.api.TweetsApi.access$6500(TweetsApi.java:87)
2022-07-13 15:38:35.600 6065-6276/com.example.trackmycrypto W/System.err:     at com.twitter.clientlib.api.TweetsApi$APItweetsRecentSearchRequest.execute(TweetsApi.java:4439)
2022-07-13 15:38:35.600 6065-6276/com.example.trackmycrypto W/System.err:     at com.example.trackmycrypto.Utils.getTwitterNews(Utils.java:736)
2022-07-13 15:38:35.600 6065-6276/com.example.trackmycrypto W/System.err:     at com.example.trackmycrypto.NewsAndMediaActivity$2.run(NewsAndMediaActivity.java:86)
2022-07-13 15:38:35.600 6065-6276/com.example.trackmycrypto W/System.err:     at java.lang.Thread.run(Thread.java:1012)
```

This code is actually part of an Android application.

I have honestly no idea how to fix this issue, as the error is unfortunately not indicative. Would you have any suggestion on how to investigate this issue or on anything that could help ?

**Comment by zacmos** [comment]
Hi, I didn't manage to recreate this error with a valid bearer token. Please make sure that the valid token is actually being set into `TwitterCredentialsBearer ` by the `System.getenv("$bearer")`
