### ISSUE TITLE
Caused by: java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by mklueh** [twitterdev/twitter-api-java-sdk#6]
I'm running into a timeout issue frequently. I guess, it happens when there is currently no item to stream. However, I'm basically using the implementation of the documentation. 

```
          BufferedReader reader = new BufferedReader(new InputStreamReader(twitterApi.tweets()
                        .searchStream(5,
                                Set.of("author_id", "referenced_tweets.id", "in_reply_to_user_id", "geo.place_id", "attachments.media_keys", "attachments.poll_ids", "entities.mentions.username", "referenced_tweets.id.author_id"),
                                Set.of("id", "created_at", "text", "author_id", "in_reply_to_user_id", "referenced_tweets", "attachments",
                                        "withheld", "geo", "entities", "public_metrics", "possibly_sensitive", "source", "lang", "context_annotations", "non_public_metrics",
                                        "promoted_metrics", "organic_metrics", "conversation_id", "reply_settings"),
                                Set.of("id", "created_at", "name", "username", "protected", "verified", "withheld", "profile_image_url", "location", "url", "description", "entities", "pinned_tweet_id", "public_metrics"),
                                Set.of("media_key", "duration_ms", "height", "preview_image_url", "type", "url", "width", "public_metrics", "non_public_metrics", "organic_metrics", "promoted_metrics", "alt_text"),
                                Set.of("id", "name", "country_code", "place_type", "full_name", "country", "contained_within", "geo"),
                                null, 0))
                );

                String line = reader.readLine();
                while (line != null) {
                    log.info(line);
                    //emitter.emit(convert(gson, line));
                    line = reader.readLine();
                }
```

```
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:409)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
	at okio.RealBufferedSource.read(RealBufferedSource.java:51)
	at okio.RealBufferedSource.request(RealBufferedSource.java:72)
	at okio.RealBufferedSource.require(RealBufferedSource.java:65)
	at okio.GzipSource.consumeHeader(GzipSource.java:114)
	at okio.GzipSource.read(GzipSource.java:73)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)

```

How can I prevent that?

**Comment by zacmos** [comment]
The `OkHttp` timeouts are [set](https://github.com/twitterdev/twitter-api-java-sdk/blob/main/src/main/java/com/twitter/clientlib/ApiClient.java#:~:text=httpClient%20%3D%20builder.connectTimeout,TimeUnit.SECONDS).build()%3B) to wait for the streaming keep alive.
Please try `v1.1.4`.
