### ISSUE TITLE
Incompatibility with spring-boot-starter-parent: okhttp3.RequestBody.create not found

### ISSUE THREAD

**Issue by gerardpuigl** [twitterdev/twitter-api-java-sdk#7]
### Expected behavior

I'm trying to set up rules to filter stream request using the method: 
https://github.com/twitterdev/twitter-api-java-sdk/blob/main/docs/TweetsApi.md#addOrDeleteRules
But adding a rules to the AddOrDeleteRulesRequest.

here my code: (simplified to isolate the problem)
```
@SpringBootApplication
public class DemoApplication implements CommandLineRunner {

  public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
  }

  @Override
  public void run(String... args) throws Exception {
    TwitterCredentialsBearer credentials = new TwitterCredentialsBearer("*************");
    TwitterApi apiInstance = new TwitterApi();
    apiInstance.setTwitterCredentials(credentials);

    // create new rules from a keywords array
    String[] keywords = {"Java", "Microservices", "Spring", "Kafka", "Elasticseach"};
    AddRulesRequest addRulesRequest = new AddRulesRequest();
    for (String keyword : keywords) {
      addRulesRequest.addAddItem(new RuleNoId().value(keyword).tag(keyword));
    }

    // Set the params values
    AddOrDeleteRulesRequest addOrDeleteRulesRequest = new AddOrDeleteRulesRequest(
        addRulesRequest); // AddOrDeleteRulesRequest |
    Boolean dryRun = true; // Boolean | Dry Run can be used with both the add and delete action, with the expected result given, but without actually taking any action in the system (meaning the end state will always be as it was when the request was submitted). This is particularly useful to validate rule changes.
    try {
      AddOrDeleteRulesResponse result = apiInstance.tweets()
          .addOrDeleteRules(addOrDeleteRulesRequest, dryRun);
      System.out.println(result);
    } catch (ApiException e) {
      System.err.println("Exception when calling TweetsApi#addOrDeleteRules");
      System.err.println("Status code: " + e.getCode());
      System.err.println("Reason: " + e.getResponseBody());
      System.err.println("Response headers: " + e.getResponseHeaders());
      e.printStackTrace();
    }
  }
}

```

### Actual behavior

But when I run the application I received this error:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at com.twitter.clientlib.ApiClient.serialize(ApiClient.java:956)
	at com.twitter.clientlib.ApiClient.buildRequest(ApiClient.java:1227)
	at com.twitter.clientlib.ApiClient.buildCall(ApiClient.java:1173)
	at com.twitter.clientlib.api.TweetsApi.addOrDeleteRulesCall(TweetsApi.java:132)
	at com.twitter.clientlib.api.TweetsApi.addOrDeleteRulesValidateBeforeCall(TweetsApi.java:144)
	at com.twitter.clientlib.api.TweetsApi.addOrDeleteRulesWithHttpInfo(TweetsApi.java:211)
	at com.twitter.clientlib.api.TweetsApi.addOrDeleteRules(TweetsApi.java:166)
	at com.example.demo.Example.main(Example.java:28)
```

Or if I run inside @SpringBootApplication
```***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.twitter.clientlib.ApiClient.serialize(ApiClient.java:956)

The following method did not exist:

    'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'

The calling method's class, com.twitter.clientlib.ApiClient, was loaded from the following location:

    jar:file:/Users/gerard.puig/.m2/repository/com/twitter/twitter-api-java-sdk/1.1.3/twitter-api-java-sdk-1.1.3.jar!/com/twitter/clientlib/ApiClient.class

The called method's class, okhttp3.RequestBody, is available from the following locations:

    jar:file:/Users/gerard.puig/.m2/repository/com/squareup/okhttp3/okhttp/3.14.9/okhttp-3.14.9.jar!/okhttp3/RequestBody.class

The called method's class hierarchy was loaded from the following locations:

    okhttp3.RequestBody: file:/Users/gerard.puig/.m2/repository/com/squareup/okhttp3/okhttp/3.14.9/okhttp-3.14.9.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes com.twitter.clientlib.ApiClient and okhttp3.RequestBody
```
I think the problem comes from use spring-boot-starter-parent created with: https://start.spring.io/

I think spring boot starter parent loads a version 4.9.2 of okhttp library and that makes that the ApiClient don't found the okhttp version 3.14.9

### Steps to reproduce the behavior

try to execute the  code above with POM.xml from [spring Initializr](https://start.spring.io/)

```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.6</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.twitter</groupId>
			<artifactId>twitter-api-java-sdk</artifactId>
			<version>1.1.3</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by gerardpuigl** [comment]
**Solution:**

After some investigations I found that the problem was just the opposite, spring-boot-starter loads the version 3.14.9 and the version defined in twitter-api-java-sdk is 4.9.2

Adding the same version to the properties sections it's solved:
```
<properties>
	<okhttp3.version>4.9.2</okhttp3.version>
</properties>
```

I don't know if this can be solved in other way but this solutions works for me.

I'm interested to learn more about this kind of incompatibilities as it's the first time I found it. If anyone can aport other point of view it would be very welcome!

**Comment by zacmos** [comment]
I think that you are correct, the method does not exist in https://javadoc.io/doc/com.squareup.okhttp3/okhttp/3.14.9/okhttp3/ResponseBody.html.
Regarding overriding the Spring Boot dependency, I found this https://www.baeldung.com/spring-boot-override-dependency-versions.

**Comment by gerardpuigl** [comment]
Hi zacmos, yes this solution is that I used! I don't know if this can be solved from your dependency when it's loading but this is outside from knowledge!

Thanks for the Api and keep working at you do! :)
